// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yxaajfqkjeutqhenoeiw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl4YWFqZnFramV1dHFoZW5vZWl3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI2ODM1NzgsImV4cCI6MjA2ODI1OTU3OH0.R1LnjRebcTD47Qhxrlw9f7L-UdZRL8LRBkwLCoL6jzg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});